// Import the wasm-bindgen generated JS wrapper and WASM binary
// @ts-ignore - Generated by wasm-bindgen
import init, { parse_log } from "./wasm/rust_log_parser.js";
// @ts-ignore - WASM binary
import wasmBinary from "./wasm/rust_log_parser_bg.wasm";

let wasmInitialized: Promise<void> | null = null;

async function ensureWasmInitialized(): Promise<void> {
    if (!wasmInitialized) {
        // Pass the WASM module as an object to avoid deprecation warning
        wasmInitialized = init({ module_or_path: wasmBinary });
    }
    await wasmInitialized;
}

export interface LogEntry {
    severity: string;
    message: string;
    timestamp: string | null;
    stack: string[];
    raw: string;
}

export interface ParsedLog {
    entries: LogEntry[];
}

/**
 * Parse raw log text using the Rust WASM module.
 * 
 * @param logText - Raw log text to parse
 * @returns Parsed log entries with severity, message, timestamp, and stack traces
 */
export async function parseLogsWithWasm(logText: string): Promise<ParsedLog> {
    await ensureWasmInitialized();
    const json = parse_log(logText);
    return JSON.parse(json);
}