export interface LogEntry {
    severity: string;
    message: string;
    timestamp: string | null;
    stack: string[];
    raw: string;
}

export interface ParsedLog {
    entries: LogEntry[];
}

/**
 * Parse raw log text using the Rust WASM module.
 * 
 * @param logText - Raw log text to parse
 * @returns Parsed log entries with severity, message, timestamp, and stack traces
 */
export async function parseLogsWithWasm(logText: string): Promise<ParsedLog> {
    // Dynamic import to avoid build errors before WASM is compiled
    try {
        // @ts-ignore - WASM module will be generated by build:wasm script
        const { default: initWasm, parse_log } = await import("./wasm/rust_log_parser.js");

        // Initialize WASM module
        await initWasm();

        // Call the parse_log function
        const json = parse_log(logText);
        return JSON.parse(json);
    } catch (error) {
        // Fallback if WASM not built yet
        console.error("WASM module not found. Run 'pnpm run build:wasm' in packages/rust_log_parser");
        throw new Error("WASM module not available. Please build the Rust log parser first.");
    }
}
